"""Create price_candles table

Revision ID: 05b82b104e99
Revises: c6bc9df6c377
Create Date: 2025-06-01 13:23:01.707557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b82b104e99'
down_revision: Union[str, None] = 'c6bc9df6c377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('auto_sell_triggered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_positions_id'), 'investment_positions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_positions_symbol'), 'investment_positions', ['symbol'], unique=False)
    op.create_table('price_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_symbol_timestamp')
    )
    op.create_index(op.f('ix_price_candles_id'), 'price_candles', ['id'], unique=False)
    op.create_index(op.f('ix_price_candles_symbol'), 'price_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_candles_timestamp'), 'price_candles', ['timestamp'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('triggered_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['investment_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_price_candles_timestamp'), table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_symbol'), table_name='price_candles')
    op.drop_index(op.f('ix_price_candles_id'), table_name='price_candles')
    op.drop_table('price_candles')
    op.drop_index(op.f('ix_investment_positions_symbol'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_id'), table_name='investment_positions')
    op.drop_table('investment_positions')
    # ### end Alembic commands ###
