"""Add alert_thresholds table

Revision ID: 0fe6d8728f92
Revises: 4a3f04ac62c7
Create Date: 2025-06-04 22:56:00.748409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe6d8728f92'
down_revision: Union[str, None] = '4a3f04ac62c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('threshold_price', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('ABOVE', 'BELOW', name='directionenum'), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_thresholds_id'), 'alert_thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_alert_thresholds_symbol'), 'alert_thresholds', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_thresholds_symbol'), table_name='alert_thresholds')
    op.drop_index(op.f('ix_alert_thresholds_id'), table_name='alert_thresholds')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
