"""Add unique constraint on symbol and timestamp in price_candles

Revision ID: 5ce0a16a89b1
Revises: fa0183555a68
Create Date: 2025-06-01 12:27:24.525485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce0a16a89b1'
down_revision: Union[str, None] = 'fa0183555a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_symbol_timestamp",  # constraint name
        "price_candles",        # table name
        ["symbol", "timestamp"] # columns
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_symbol_timestamp",  # constraint name
        "price_candles",        # table name
        type_="unique"
    )
    # ### end Alembic commands ###
