"""add created_at to investment_positions

Revision ID: 8415db0cbf5a
Revises: 681eb1e161cf
Create Date: 2025-05-18 19:29:09.225114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8415db0cbf5a'
down_revision: Union[str, None] = '681eb1e161cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_positions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_positions', 'created_at')
    # ### end Alembic commands ###
