"""Add phone_alert and app_alert to alert_thresholds

Revision ID: bf8236782fde
Revises: abe7c3bf25f3
Create Date: 2025-06-10 21:18:12.126731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8236782fde'
down_revision: Union[str, None] = 'abe7c3bf25f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_thresholds', sa.Column('phone_alert', sa.Boolean(), nullable=True))
    op.add_column('alert_thresholds', sa.Column('app_alert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_thresholds', 'app_alert')
    op.drop_column('alert_thresholds', 'phone_alert')
    # ### end Alembic commands ###
