"""Create price_candles table

Revision ID: c6bc9df6c377
Revises: c1a7b6204027
Create Date: 2025-06-01 13:20:14.512803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6bc9df6c377'
down_revision: Union[str, None] = 'c1a7b6204027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_rules_id', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_investment_positions_id', table_name='investment_positions')
    op.drop_index('ix_investment_positions_symbol', table_name='investment_positions')
    op.drop_table('investment_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_positions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('investment_positions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('auto_sell_triggered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='investment_positions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_investment_positions_symbol', 'investment_positions', ['symbol'], unique=False)
    op.create_index('ix_investment_positions_id', 'investment_positions', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triggered_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['investment_positions.id'], name='alert_rules_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alert_rules_pkey')
    )
    op.create_index('ix_alert_rules_id', 'alert_rules', ['id'], unique=False)
    # ### end Alembic commands ###
