name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: investment_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: investment_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do echo "Waiting for PostgreSQL..."; sleep 1; done

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings --maxfail=1

      - name: Generate coverage report
        run: |
          coverage run -m pytest tests/
          coverage report
          coverage xml

        # - name: Upload coverage to Codecov (optional)
        #   if: success()
        #   uses: codecov/codecov-action@v4
        #   with:
        #     token: ${{ secrets.CODECOV_TOKEN }} # Set this in GitHub repo secrets
        #     files: coverage.xml
